-- Users authenticated via Google OAuth.
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  google_sub TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL DEFAULT '',
  name TEXT NOT NULL DEFAULT '',
  picture TEXT NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

-- Browser sessions for this web app (cookie token is stored hashed).
CREATE TABLE IF NOT EXISTS public.app_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  created_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL,
  last_seen_at BIGINT NOT NULL,
  user_agent TEXT NOT NULL DEFAULT '',
  last_ip TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_app_sessions_user_id ON public.app_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_app_sessions_expires_at ON public.app_sessions(expires_at);

-- Telegram MTProto session saved per app user (encrypted in application layer).
CREATE TABLE IF NOT EXISTS public.telegram_sessions (
  user_id BIGINT PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
  session_encrypted TEXT NOT NULL,
  updated_at BIGINT NOT NULL
);

-- Desktop bearer sessions (non-cookie auth for desktop app).
CREATE TABLE IF NOT EXISTS public.desktop_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  created_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL,
  last_seen_at BIGINT NOT NULL,
  user_agent TEXT NOT NULL DEFAULT '',
  last_ip TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_desktop_sessions_user_id ON public.desktop_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_desktop_sessions_expires_at ON public.desktop_sessions(expires_at);

-- Temporary intents for desktop OAuth handoff.
CREATE TABLE IF NOT EXISTS public.desktop_auth_intents (
  intent_code TEXT PRIMARY KEY,
  poll_secret_hash TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_desktop_auth_intents_expires_at ON public.desktop_auth_intents(expires_at);
